version: '3.8'

services:
  phuket_info_bot:
    container_name: phuket-info-bot
    image: node:18-buster
    build:
      context: ./
    networks:
      - app
    depends_on:
      - db
    links:
      - db
    env_file: .env
    ports:
     - '4243:4243'
    volumes:
      - ./:/bot

  db:
    image: redis:7.0.7-alpine
    restart: always
    env_file: .env
    command: redis-server --save 20 1 --loglevel warning --requirepass $DB_PASSWORD
    ports:
      - '6379:6379'
    volumes:
      - db-data:/etc/data
    networks:
      - app

volumes:
  db-data:
    driver: local

networks:
  app:
    driver: default