version: '3.9'

services:
  bot:
    image: node:18-buster
    restart: on-failure
    build:
      context: ./
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./:/bot
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4243" ]
      interval: 30s
      timeout: 15s
      retries: 5

  db:
    image: redis:7.0.7-alpine
    restart: always
    env_file: .env
    command: redis-server --save 20 1 --loglevel warning --requirepass $DB_PASSWORD
    ports:
      - '6379:6379'
    volumes:
      - db-data:/etc/data

  web:
    build: ./nginx
    restart: always
    depends_on:
      bot:
        condition: service_healthy
    ports:
      - '4242:80'

volumes:
  db-data:
    driver: local
